/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alberto's PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private boolean fiche;
    private boolean ficheno;
    private double tini, tfin;
    private Lector mf;
    private Perimetros ex;
    private FicheroGNU fGNU;
    private ArrayList<Puntos> vector = new ArrayList<>();
    private ArrayList<Puntos> vectorSol = new ArrayList<>();
    private ArrayList<ArrayList<Puntos>> camino = new ArrayList<>();

    public Menu() {
        initComponents();
        fiche = false;
        ficheno = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Fichero = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VectorTam = new javax.swing.JTextField();
        carsi = new javax.swing.JButton();
        carno = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        BE = new javax.swing.JButton();
        DYV = new javax.swing.JButton();
        Prim = new javax.swing.JButton();
        Kruskal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        primNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fichero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "berlin52", "ch130", "ch150", "d493" }));

        jLabel1.setText("Elija el fichero que quiere cargar:");

        jLabel2.setText("Cargar fichero:");

        jLabel3.setText("Ingrese el tamaño deseado :");

        carsi.setText("Si");
        carsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsiActionPerformed(evt);
            }
        });

        carno.setText("No");
        carno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carnoActionPerformed(evt);
            }
        });

        cargar.setText("CARGAR");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        BE.setText("Busqueda Exhaustiva");
        BE.setEnabled(false);
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });

        DYV.setText("Divide y venceras");
        DYV.setEnabled(false);
        DYV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DYVActionPerformed(evt);
            }
        });

        Prim.setText("Prim");
        Prim.setEnabled(false);
        Prim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimActionPerformed(evt);
            }
        });

        Kruskal.setText("Kruscal");
        Kruskal.setEnabled(false);
        Kruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KruskalActionPerformed(evt);
            }
        });

        consola.setColumns(20);
        consola.setRows(5);
        consola.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        consola.setEnabled(false);
        jScrollPane2.setViewportView(consola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(VectorTam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(cargar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(Fichero, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(carno, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(carsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BE)
                                .addGap(18, 18, 18)
                                .addComponent(DYV)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(primNum)
                                    .addComponent(Prim, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Kruskal)))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(carsi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carno)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(VectorTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargar))
                .addGap(59, 59, 59)
                .addComponent(primNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BE)
                    .addComponent(DYV)
                    .addComponent(Kruskal)
                    .addComponent(Prim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsiActionPerformed
        // TODO add your handling code here:
        carsi.setBackground(Color.green);
        carno.setBackground(Color.LIGHT_GRAY);
        fiche = true;
        ficheno = false;
    }//GEN-LAST:event_carsiActionPerformed

    private void carnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carnoActionPerformed
        // TODO add your handling code here:
        carno.setBackground(Color.green);
        carsi.setBackground(Color.LIGHT_GRAY);
        fiche = false;
        ficheno = true;
    }//GEN-LAST:event_carnoActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
        if (fiche == true) {
            String f = (String) Fichero.getSelectedItem() + ".tsp";
            mf = new Lector(f);
            mf.leeFichero(vector);
        } else if (ficheno == true) {
            int tama = Integer.parseInt(VectorTam.getText());
            Random rand = new Random();
            for (int i = 0; i < tama; i++) {
                Puntos paux = new Puntos(i, rand.nextFloat(), rand.nextFloat());
                vector.add(paux);
            }
        }
        Kruskal.setEnabled(true);
        Prim.setEnabled(true);
        DYV.setEnabled(true);
        BE.setEnabled(true);
    }//GEN-LAST:event_cargarActionPerformed

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
        consola.setText("");
        ex = new Perimetros();
        tini = System.currentTimeMillis();
        float tam = ex.Busqueda(vector, vectorSol, 0);
        tfin = System.currentTimeMillis();
        String s = "Tiempo total : \t" + (tfin - tini);
        consola.append("Busqueda Exhaustiva \n");
        consola.append(s + "\n");
        consola.append("Perimetro: \t" + tam);
        fGNU = new FicheroGNU();
        try {
            fGNU.Comandos();
            fGNU.Conjunto(vector);
            fGNU.Solucion(vectorSol);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BEActionPerformed

    private void DYVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DYVActionPerformed
        // TODO add your handling code here:
        consola.setText("");
        HeapSort heap = new HeapSort();
        vectorSol.clear();
        DivVenc dv = new DivVenc(vector);
        fGNU = new FicheroGNU();
        tini = System.currentTimeMillis();
        heap.ordenaMonticulos(vector);
        vectorSol = dv.triangulo(vector);
        float sol = dv.per();
        tfin = System.currentTimeMillis();
        String s = "Tiempo total : \t" + (tfin - tini);
        consola.append("Divide y Venceras \n");
        consola.append(s + "\n");
        consola.append("Perimetro: \t" + sol);
        try {
            fGNU.Comandos();
            fGNU.Conjunto(vector);
            fGNU.Solucion(vectorSol);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DYVActionPerformed

    private void PrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimActionPerformed
        // TODO add your handling code here:
        consola.setText("");
        Prim p = new Prim();
        int num = Integer.parseInt(primNum.getText());
        tini = System.currentTimeMillis();
        p.CaminoPrim(vector, camino, num);
        tfin = System.currentTimeMillis();
        float sol = p.per();
        String s = "Tiempo total : \t" + (tfin - tini);
        consola.append("Prim \n");
        consola.append(s + "\n");
        consola.append("Perimetro: \t" + sol);
        fGNU = new FicheroGNU();
        try {
            fGNU.ComandosArbol();
            fGNU.arbol(camino);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrimActionPerformed

    private void KruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KruskalActionPerformed
        // TODO add your handling code here:
        consola.setText("");
        Kruscal c = new Kruscal();
        tini = System.currentTimeMillis();
        c.CaminoKrus(vector, camino);
        tfin = System.currentTimeMillis();
        double sol = c.per();
        System.out.println("Tiempo Total: " + (tfin - tini));
        String s = "Tiempo total : \t" + (tfin - tini);
        consola.append("Kruscal \n");
        consola.append(s + "\n");
        consola.append("Perimetro: \t" + sol);
        fGNU = new FicheroGNU();
        try {
            fGNU.ComandosArbol();
            fGNU.arbol(camino);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_KruskalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BE;
    private javax.swing.JButton DYV;
    private javax.swing.JComboBox<String> Fichero;
    private javax.swing.JButton Kruskal;
    private javax.swing.JButton Prim;
    private javax.swing.JTextField VectorTam;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cargar;
    private javax.swing.JButton carno;
    private javax.swing.JButton carsi;
    private javax.swing.JTextArea consola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField primNum;
    // End of variables declaration//GEN-END:variables
}
